apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: configmap-extra-resources
parameters:
- name: JUPYTERHUB_NAMESPACE
  value: ""
  required: true
- name: JUPYTERHUB_APPLICATION
  value: ""
  required: true
objects:
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: ${JUPYTERHUB_APPLICATION}-res
    namespace: ${JUPYTERHUB_NAMESPACE}
    labels:
      app: ${JUPYTERHUB_APPLICATION}
  data:
    extra_resources.json: |-
      {
        "kind": "List",
        "apiVersion": "v1",
        "items": [
          {
            "kind": "SecurityContextConstraints",
            "apiVersion": "security.openshift.io/v1",
            "metadata": {
              "name": "${project_namespace}-anyuid",
              "labels": {
                "app": "${JUPYTERHUB_APPLICATION}-${JUPYTERHUB_NAMESPACE}",
                "project": "${project_namespace}"
              }
            },
            "priority": 888,
            "runAsUser": {
              "type": "RunAsAny"
            },
            "seLinuxContext": {
              "type": "MustRunAs"
            },
            "users": [
              "system:serviceaccount:${project_namespace}:default"
            ],
              "volumes": [
              "configMap",
              "downwardAPI",
              "emptyDir",
              "persistentVolumeClaim",
              "projected",
              "secret"
            ]
          },
          {
            "kind": "ServiceAccount",
            "apiVersion": "v1",
            "metadata": {
              "name": "couchbase-operator"
            }
          },
          {
            "kind": "RoleBinding",
            "apiVersion": "rbac.authorization.k8s.io/v1beta1",
            "metadata": {
              "name": "couchbase-operator-rolebinding"
            },
            "subjects": [
              {
                "kind": "ServiceAccount",
                "name": "couchbase-operator"
              }
            ],
            "roleRef": {
              "kind": "ClusterRole",
              "apiGroup": "rbac.authorization.k8s.io",
              "name": "couchbase-operator"
            }
          },
          {
            "apiVersion": "apps/v1",
            "kind": "Deployment",
            "metadata": {
              "name": "couchbase-operator"
            },
            "spec": {
              "replicas": 1,
              "selector": {
                "matchLabels": {
                  "app": "couchbase-operator"
                }
              },
              "template": {
                "metadata": {
                  "labels": {
                    "app": "couchbase-operator"
                  }
                },
                "spec": {
                  "containers": [
                    {
                      "name": "couchbase-operator",
                      "image": "couchbase/operator:1.1.0",
                      "command": [
                        "couchbase-operator"
                      ],
                      "args": [
                        "-enable-upgrades=false"
                      ],
                      "env": [
                        {
                          "name": "MY_POD_NAMESPACE",
                          "valueFrom": {
                            "fieldRef": {
                              "fieldPath": "metadata.namespace"
                            }
                          }
                        },
                        {
                          "name": "MY_POD_NAME",
                          "valueFrom": {
                            "fieldRef": {
                              "fieldPath": "metadata.name"
                            }
                          }
                        }
                      ],
                      "ports": [
                        {
                          "name": "readiness-port",
                          "containerPort": 8080
                        }
                      ],
                      "readinessProbe": {
                        "httpGet": {
                          "path": "/readyz",
                          "port": "readiness-port"
                        },
                        "initialDelaySeconds": 3,
                        "periodSeconds": 3,
                        "failureThreshold": 19
                      }
                    }
                  ],
                  "serviceAccountName": "couchbase-operator"
                }
              }
            }
          }
        ]
      }
